services:
  server:
      image: node
      # build: .
      depends_on:
        - db
      ports: 
          - 3000:3000
      environment:
        APP_PORT: 3000
      working_dir: /server
      command: npm run dev # "dev": "nodemon -L ./app.ts",
        # - npm i && nodemon app.ts (-)-ov greladzevy chi ashxatum
      volumes:
        - ./server:/server
  client:
      # image: node
      # image: node:alpine
      build: ./client
      depends_on:
        - db
        - server
      ports: 
          - 5173:8000
      # working_dir: /client
      command: sh -c "npm rebuild esbuild && npm run dev" # "dev": "nodemon -L ./app.ts",
      #   # - npm i && nodemon app.ts (-)-ov greladzevy chi ashxatum
      volumes:
        - ./client:/client
      # tty: true
  db:
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: root
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
   pgdata:


